/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("dev.bardin.telebot.java-application-conventions")
}

dependencies {
    // implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    // mainClass.set("dev.bardin.telebot.app.CalendarHandler")
}
